services: 
  db: 
    image: postgres:18-trixie
    restart: always
    container_name: roadmap-homework-db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  minio:
    image: minio/minio
    restart: always
    container_name: roadmap-homework-minio
    command: server --console-address ":9001" /data
    ports:
      - "${MINIO_PORT}:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
       MINIO_ROOT_USER: ${MINIO_ROOT_USER}
       MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

  create-minio-buckets:
    image: minio/mc
    depends_on:
      - minio
    restart: "no"
    entrypoint: 
      /bin/sh -c "
      set -e;
      sleep 5;
      /usr/bin/mc alias set dockerminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb --ignore-existing dockerminio/${MINIO_USERS_AVATARS_BUCKET};
      "
  redis:
    image: redis:8.6.2-alpine
    restart: always
    container_name: roadmap-homework-redis
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --save 60 1000
    volumes: 
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  minio_storage:
  postgres_data:
  redis_data: